<html>
    <head>
        <script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
        <title>01-introduction</title>
        <!-- Load Polymer -->
<!--        <script
            src="../public/components/platform/platform.js">
        </script>
     
        <link rel="import"
              href="../public/components/core-toolbar/core-toolbar.html">
        <link rel="import"
              href="../public/components/core-drawer-panel/core-drawer-panel.html">
        <link rel="import"
              href="../public/components/core-header-panel/core-header-panel.html">
        <link rel="import"
              href="../public/components/core-item/core-item.html">
        <link rel="import"
              href="../public/components/core-icons/core-icons.html">
        <link rel="import"
              href="../public/components/paper-icon-button/paper-icon-button.html">
        <link rel="import"
              href="../public/components/paper-menu-button/paper-menu-button.html">
        <link rel="import"
              href="../public/components/paper-item/paper-item.html">
        <link rel="import"
              href="../public/components/paper-tabs/paper-tabs.html">
        <link rel="import"
              href="../public/components/paper-input/paper-input.html">

        <link rel="import"
              href="../public/components/paper-dialog/paper-dialog.html">
        <link rel="import"
              href="../public/components/paper-button/paper-button.html">

         NEW ELEMENTS 
        <link rel="import"
              href="../public/components/core-form-inscription/core-form-inscription.html">     
        <link rel="import"
              href="../public/components/core-form-connexion/core-form-connexion.html">  
         STYLESHEETS 

        <link rel="stylesheet" href="style/CSS.css" type="text/css">
        <link rel="stylesheet" href="style/shadow-dom.css" type="text/css">
         FONTS 
        <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="cssSlider created with cssSlider, a free wizard program that helps you easily generate beautiful web slideshow" />-->


        <style shim-shadowdom>


            section {
                padding: 20px 0;
            }

            section > div {
                padding: 14px;
                font-size: 16px;
            }

            button{
                margin: 8px 4px;
            }

            html /deep/ [autofocus] {
                color: #03a9f4;
            }

            html /deep/ .scrolling::shadow #scroller {
                height: 350px;
            }

            html /deep/ .colored {
                border: 1px solid #0f9d58;
                background-color: #b7e1cd;
                color: #0f9d58;
            }

            html /deep/ .size-position {
                position: fixed;
                top: 156px;

                right: 150px;
                left: 65%;
            }

            html /deep/ .size-position::shadow #scroller {
                width: 300px;
                height: 300px;
            }

        </style>





    </head>
<!--    <body fullbleed vertical layout unresolved>

    <core-drawer-panel id="drawerPanel">

        <core-header-panel drawer vertical layout id="left-menu">
            <core-toolbar class="medium-tall" id="barre"><h2>BEin3D</h2></core-toolbar>
            <core-menu>
                                <core-item label="Shop"></core-item>
                <core-item label="Design"></core-item>
                <core-item label="Sell"></core-item>
                            </core-menu>
        </core-header-panel>

        <core-header-panel main >
            <core-toolbar class="medium-tall" id="barre2">
                 TOP TOOLBAR 
                <core-icon-button id="navicon" icon="menu" on-tap="{{menuAction}}"></core-icon-button>
                <paper-tabs flex selected="{{selected}}">
                    <paper-tab id="shop">SHOP</paper-tab>
                    <paper-tab id="design">DESIGN</paper-tab>
                    <paper-tab>SELL</paper-tab>
                </paper-tabs>
                <paper-input id="search-mainpage-input" label="Rechercher"></paper-input>
                <paper-icon-button icon="search"></paper-icon-button>

                <template is="auto-binding">
                    <paper-button   label="CONNEXION" on-tap="{{toggleDialog1}}" ></paper-button>
                    <paper-dialog heading="Connexion" class="size-position">
                        <core-form-connexion>           
                        </core-form-connexion> 
                    </paper-dialog>
                </template>

                <paper-button  id="inscription-button" label="INSCRIPTION" onclick="toggleDialog('paper-dialog-transition-center')"></paper-button>
                <paper-dialog heading="Inscription" transition="paper-dialog-transition-center">


                    <core-form-inscription>           
                    </core-form-inscription>

                </paper-dialog>
                <!-- BOTTOM TOOLBAR 

                <div class="bottom" id="sous-menu"> 

                <paper-tabs class="bottom" flex selected="{{selected}}">
                    <paper-tab>+POPULAIRES</paper-tab>
                    <paper-tab>NOUVEAUTES</paper-tab>
                    <paper-tab>ART</paper-tab>
                    <paper-tab>MEILLEURS MAKERS</paper-tab>
                    <paper-tab>CONCOURS</paper-tab>
                </paper-tabs>                

            </core-toolbar>-->


            <div id="connect">
                Utilisateur ou mot de passe incorrect
                <center>
                <core-form-connexion>           
                </core-form-connexion> 
                    </center>
            </div>
<!--            <div id="shop-content" class="hide">
                <table>
                    <tr> 
                        <?php
//                        for ($i = 0; $i < 100; $i++) {
//                            echo "<td>";
//                            echo "<div id='produit'>adazdaz</div>";
//                            echo "</td>";
//                        }
                        ?>
                    </tr>
                </table>
            </div>
            <div id="design-content" class="hide">
                <center> ntm
                </center>

            </div>-->
        </core-header-panel>

    </core-drawer-panel>


</core-header-panel>
<polymer-element name="component-form" extends="form" on-submit="{{ prepareSubmit }}" on-click="{{ handleClick }}">
    <script>
        Polymer('component-form', {
            handleClick: function (event, detail, sender) {
                if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'submit') {
                    this.prepareSubmit();
                    this.submit();
                }
                if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'reset') {

                    this.form.reset();
                }

            },
            prepareSubmit: function () {
                Array.prototype.forEach.call(this.children, function (child) {
                    var name = child.getAttribute('name');
                    // Add <input type="hidden">s for all custom elements with a name and value besides submit buttons
                    if (child.localName.indexOf('-') !== -1 && name && 'value' in child && child.getAttribute('type') !== 'submit') {
                        element = document.createElement('input');
                        element.setAttribute('type', 'hidden');
                        element.setAttribute('name', name);
                        element.setAttribute('value', child.value);
                        this.appendChild(element);
                    }
                }.bind(this));
            },
        });
    </script>
</polymer-element>



</body>

</html>
<script type="text/javascript">
    $("#shop").click(function () {
        if (!$('#design-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#design-content').toggleClass("hide");
        }
           if (!$('#connect').hasClass('hide')) { // it checks if mobile_billing is not open
             $('#connect').toggleClass("hide");
        }
       
        $('#shop-content').toggleClass("hide");



    });
    $("#design").click(function () {
        if (!$('#shop-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#shop-content').toggleClass("hide");
        }
        if (!$('#connect').hasClass('hide')) { // it checks if mobile_billing is not open
             $('#connect').toggleClass("hide");
        }
        $('#design-content').toggleClass("hide");



    });

//
//    function addName() {
//        var recup = document.querySelectorAll("hello-john-doe")[0];
//        document.querySelector("buddies-list").buddies.push({name: recup.name});
//    }
//    ;
    function toggleDialog(transition) {
        var dialog = document.querySelector('paper-dialog[transition=' + transition + ']');
        dialog.toggle();
    }
    ;


    function recupinfo() {
        var login = document.querySelectorAll("paper-input")[1];
        document.getElementById('affiche').innerHTML = login.inputValue;

        var mdp = document.querySelectorAll("paper-input")[2];


        var Cmdp = document.querySelectorAll("paper-input")[3];
        if (mdp != Cmdp) {
            document.getElementById('affiche').innerHTML = "Veuillez confirmez votre mot de passe."
        }

        var email = document.querySelectorAll("paper-input")[4];
        document.getElementById('affiche').innerHTML = login.inputValue;
    }
    var scope = document.querySelector('template[is=auto-binding]');

    scope.toggleDialog1 = function (e) {
//        if (e.target.localName != 'paper-button') {
//            return;
//        }
        var d = e.target.nextElementSibling;
        if (!d) {
            return;
        }
        d.toggle();
    };



</script>