<html>
    <head>
        
        <?php
            require '../public/requires/head-import.php';
        ?>


    </head>
    <body fullbleed vertical layout unresolved>

    <core-drawer-panel  id="drawerPanel">

        <paper-hidden-bar></paper-hidden-bar>
        <template is="auto-binding"> 
        <core-header-panel main >
            <core-toolbar class="medium-tall" id="barre2">
                <!-- TOP TOOLBAR -->
                <core-icon-button id="navicon" icon="menu" on-tap="{{menuAction}}"></core-icon-button>
                <paper-tabs flex selected="{{menu}}" valueattr="menu-cat">
                    <paper-tab menu-cat="home">HOME</paper-tab>
                    <paper-tab menu-cat="shop">SHOP</paper-tab>
                    <paper-tab menu-cat="design">DESIGN</paper-tab>
                    <paper-tab menu-cat="sell">SELL</paper-tab>
                </paper-tabs>
                <paper-input id="search-mainpage-input" label="Rechercher"></paper-input>
                <paper-icon-button icon="search"></paper-icon-button>

                <template is="auto-binding">
                    <paper-button   label="CONNEXION" on-tap="{{toggleDialog1}}" ></paper-button>
                    <paper-dialog heading="Connexion" class="size-position">
                        <core-form-connexion>           
                        </core-form-connexion> 
                    </paper-dialog>
                </template>

                <paper-button  id="inscription-button" label="INSCRIPTION" onclick="toggleDialog('paper-dialog-transition-center')"></paper-button>
                <paper-dialog heading="Inscription" transition="paper-dialog-transition-center">

                    <core-form-inscription>           
                    </core-form-inscription>

                </paper-dialog><!--
                <!-- BOTTOM TOOLBAR -->

                <core-pages class="bottom" selected="{{menu}}" valueattr="menu-cat" fullbleed>
                    
                        <paper-tabs  menu-cat="home" flex selected="{{}}">                            
                            <paper-tab>ART</paper-tab>
                            <paper-tab>MEILLEURS MAKERS</paper-tab>
                            <paper-tab>CONCOURS</paper-tab>
                        </paper-tabs>
                    
                    
                    <paper-button label="ok" menu-cat="shop"></paper-button>
                    
                        <core-item menu-cat="design">
                            <paper-tabs  flex selected="{{}}">                            
                            <paper-tab>ART</paper-tab>
                            <paper-tab>MEILLEURS MAKERS</paper-tab>
                            <paper-tab>CONCOURS</paper-tab>
                        </paper-tabs>
                            <paper-button label="ok"></paper-button>
                            <paper-button label="ok"></paper-button>
                        </core-item>
                    <core-item menu-cat="design">
                            <a href="../public/" target="_self">CHOIX2</a>
                        </core-item>
                    </div>
                    
                </core-pages>
                                
                <!--</div>-->          
            </core-toolbar>
            
            <core-pages selected="{{menu}}" valueattr="menu-cat">
                <paper-tabs  menu-cat="home" flex selected="{{0}}">                            
                    <paper-tab href="../">ART</paper-tab>
                            <paper-tab>MEILLEURS MAKERS</paper-tab>
                            <paper-tab>CONCOURS</paper-tab>
                        </paper-tabs>
                <paper-tabs  menu-cat="shop" flex selected="{{0}}">                            
                            <paper-tab>NOUVEAUTES</paper-tab>
                            <paper-tab>MEILLEURS MAKERS</paper-tab>
                            <paper-tab>LOTO 3D</paper-tab>
                        </paper-tabs>
            </core-pages>
            <core-pages selected="{{menu}}" valueattr="menu-cat">
                <section menu-cat="home">
                    <div id="accueil-content" >
                <div id="grosbloc" fullbleed>accueil</div>
                <hr/>
                <div id="grosbloc" fullbleed>
                    <div id="blockgauche">
                        <h2>3D CONCEPT ! </h2>
                        Vous voulez créer votre propre fichier 3D ?
                        <br/>
                        Vendre vos propres modèles ?
                        <br/>
                        <p> Grace à l'impression 3D, vous pouvez laisser libre court à votre imagination et concevoir un produit dans ses mondres détails.</p>
                    </div>
                    <div id="blockdroite">
                        <img src='../public/image/Image1.PNG'>
                        <br/>
                        Laissez parler l'artiste 3D qui est en vous ! &nbsp; Découvrer 3D Concept !<core-icon-button icon="add-circle" tittle="add"></core-icon-button>
                    </div>
                </div>
                <hr/>
                <div id="grosblock" fullbleed>
                    <center><h2>Avec l'impression 3D c'est vous la star ! </h2></center>
                    <div id='petitblock'>
                        <img src='../public/image/Image2.PNG'>
                        <br/>
                        Des masques 3D à votre image...ou celle des autres !
                        <br/>
                        Créer le votre! <core-icon-button icon='add-circle'></core-icon-button>
                    </div>
                    <div id='petitblock'>
                        <img src='../public/image/Image3.PNG'>
                        <br/>
                        Des figurines 3D à partir de votre photo 2D ! 
                    </div>
                </div>

                <div id='petitbloc1'>

                    <table>
                        <th>DE JOLIE PUZZLE 3D A IMPRIMER !</th>
                        <tr><td><img src='../public/image/Image4.PNG'></td></tr>
                        <tr><td>De 5 à 185 pièces, une centaines de combinaisons de couleurs </td></tr>
                        <tr><td>possibles pour un prix plancher de 15€ par puzzle, Créer le votre <core-icon-button icon="add-circle"></core-icon-button> </td></tr>

                    </table>
                    <table id="top">
                        <th>TOP DU MOIS!</th>
                        <tr></tr>
                        <tr><td><center>VISITER NOTRE BOUTIQUE</center></td></tr>
                        <tr><td><img src='../public/image/images5.PNG'></td></tr>

                    </table>
                    
                    <table id="bot">
                        <th>AVIS AUX COLLECTIONNEURS !</th>
                        <tr><td>Fan de mangas,figurines héroic fantasy,monstres,voitures,avions ...</td></tr>
                         <tr><td>Quelques soient vos envies nous les réalisons...</td></tr>
                        <tr><td><img src='../public/image/image6.PNG'></td></tr>

                    </table>
                </div>
                <div id="gauche">
                        <h1>Mes Actus</h1>
                         <ul id="actus">
                         <?php include_once 'C:\wamp\www\bein3d\application\views\scripts\Recup\index.phtml'; ?>
                             </ul>
                    </div>
                

                    <div id="footer">
                        <table id="contact"  >
                            <tr>
                                <td>Be in 3D <br/> 145 AVENUE DES CHAMPS ELYSEES <br/> 75008 PARIS CEDEX<BR/> Tel : 01.45.56.25.33 <br/> Fax : 01.45.56.55.58</td>
                                <td><paper-input id="contact-champs" label="Name" ></paper-input> <paper-input id="contact-champs" class="floated-label" label="Message"></paper-input>
                                    <paper-input id="contact-champs" label="Email"></paper-input>
                                    <paper-input id="contact-champs" label="Subject"></paper-input></td>
                                <td></td>
                            </tr>
                        </table>
                    </div>
                </div>
                </section>
                <section menu-cat="shop">
                    <h1>Shop</h1>
                    <center><table class="catalogue" cellspacing="60">
                        <tr>
                            <?php
                            $cmp=1;
                            foreach ($this->lesProduits as $produit) {
                                echo "<td class='produit-catalogue'>"
                                . "<paper-shadow z='1' animated>";                                    
                                echo "<img src='../public/image/produits/$produit->image'>";
                                echo "<h4>$produit->nom</h4>";
                                //echo "<p class='nom'>";
                                echo "<span flex><p class='prix-produit'>$produit->prixunitaire €</p>";
                                echo "<paper-button raised role='button' class='like'>"
                                . "<core-icon icon='favorite'></core-icon></paper-button>";
                                echo "<paper-button raised role='button' class='add-panier'>"
                                . "<core-icon icon='add-shopping-cart'></core-icon></paper-button>";
                                echo "</paper-shadow></td>";
                                $cmp++;
                                if($cmp>3){
                                    $cmp=0;
                                    echo"</tr><tr>";
                                }
                            }
                            ?>
                        </tr>
                        </table></center>
                        
                </section>
                <section menu-cat="design">
                    <h1>Design</h1>
                </section>
                <section menu-cat="sell">
                    <h1>Sell</h1>
                </section>
            </core-pages>
          
        </core-header-panel>
        </template>

    </core-drawer-panel>

    <polymer-element name="component-form" extends="form" on-submit="{{ prepareSubmit }}" on-click="{{ handleClick }}">
        <script>
            Polymer('component-form', {
                handleClick: function (event, detail, sender) {
                    if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'submit') {
                        this.prepareSubmit();
                        this.submit();
                    }
                    if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'reset') {

                        this.form.reset();
                    }

                },
                prepareSubmit: function () {
                    Array.prototype.forEach.call(this.children, function (child) {
                        var name = child.getAttribute('name');
                        // Add <input type="hidden">s for all custom elements with a name and value besides submit buttons
                        if (child.localName.indexOf('-') !== -1 && name && 'value' in child && child.getAttribute('type') !== 'submit') {
                            element = document.createElement('input');
                            element.setAttribute('type', 'hidden');
                            element.setAttribute('name', name);
                            element.setAttribute('value', child.value);
                            this.appendChild(element);
                        }
                    }.bind(this));
                },
            });

        </script>
    </polymer-element>



</body>

</html>
<script type="text/javascript">
//
//    function addName() {
//        var recup = document.querySelectorAll("hello-john-doe")[0];
//        document.querySelector("buddies-list").buddies.push({name: recup.name});
//    }
//    ;
    function toggleDialog(transition) {
        var dialog = document.querySelector('paper-dialog[transition=' + transition + ']');
        dialog.toggle();
    }
    ;


    function recupinfo() {
        var login = document.querySelectorAll("paper-input")[1];
        document.getElementById('affiche').innerHTML = login.inputValue;

        var mdp = document.querySelectorAll("paper-input")[2];


        var Cmdp = document.querySelectorAll("paper-input")[3];
        if (mdp != Cmdp) {
            document.getElementById('affiche').innerHTML = "Veuillez confirmez votre mot de passe."
        }

        var email = document.querySelectorAll("paper-input")[4];
        document.getElementById('affiche').innerHTML = login.inputValue;
    }
    var scope = document.querySelector('template[is=auto-binding]');

    scope.toggleDialog1 = function (e) {
//        if (e.target.localName != 'paper-button') {
//            return;
//        }
        var d = e.target.nextElementSibling;
        if (!d) {
            return;
        }
        d.toggle();
    };



</script>