<script>
    $(document).ready(function(){
                var tmp=document.querySelector('#super-template');
                tmp.menu='home';
                tmp.sub='accueil';             
            });
</script>
<style>
    .pano{
        width:100%;
        -moz-box-shadow: 1px 1px 15px 0px #656565;
        -webkit-box-shadow: 1px 1px 15px 0px #656565;
        -o-box-shadow: 1px 1px 15px 0px #656565;
        box-shadow: 1px 1px 15px 0px #656565;
        filter:progid:DXImageTransform.Microsoft.Shadow(color=#656565, Direction=134, Strength=15);
    }
</style>
<div class="contenu">
    <img class='pano' src='../public/images/panorama.jpg'>
    <h2>Bienvenue sur BEin3D</h2>
    <h3>Le site de l'impression 3D en ligne</h3>
</div>


<!--
<polymer-element name="component-form" extends="form" on-submit="{{ prepareSubmit }}" on-click="{{ handleClick }}">
    <script>
        Polymer('component-form', {
            handleClick: function (event, detail, sender) {
                if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'submit') {
                    this.prepareSubmit();
                    this.submit();
                }
                if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'reset') {

                    this.form.reset();
                }

            },
            prepareSubmit: function () {
                Array.prototype.forEach.call(this.children, function (child) {
                    var name = child.getAttribute('name');
                    // Add <input type="hidden">s for all custom elements with a name and value besides submit buttons
                    if (child.localName.indexOf('-') !== -1 && name && 'value' in child && child.getAttribute('type') !== 'submit') {
                        element = document.createElement('input');
                        element.setAttribute('type', 'hidden');
                        element.setAttribute('name', name);
                        element.setAttribute('value', child.value);
                        this.appendChild(element);
                    }
                }.bind(this));
            },
        });

    </script>
</polymer-element>

<script type="text/javascript">
//
//    function addName() {
//        var recup = document.querySelectorAll("hello-john-doe")[0];
//        document.querySelector("buddies-list").buddies.push({name: recup.name});
//    }
//    ;
    function toggleDialog(transition) {
        var dialog = document.querySelector('paper-dialog[transition=' + transition + ']');
        dialog.toggle();
    }
    ;

    var MonTableau = new Array();


    var scope = document.querySelector('template[is=auto-binding]');

    scope.toggleDialog1 = function (e) {
//        if (e.target.localName != 'paper-button') {
//            return;
//        }
        var d = e.target.nextElementSibling;
        if (!d) {
            return;
        }
        d.toggle();
    };

    var content = document.getElementById('super-template');
    //alert(content);
    var nav = document.getElementById('navicon');
    //alert(nav);
    content.addEventListerner('template-bound', function () {
        console.log(document.query - selector('navicon'));
    })

//    document.addEventListener('polymer-ready', function(){
//        var navicon=document.getElementById('navicon');
//        alert(navicon);
//        var drawerPanel=document.getElementById('drawerPanel');
//        navicon.addEventListener('click',function(){
//            drawerPanel.togglePanel();
//        });
//    });





</script>-->