<html>
    <head>

        <?php
        require '../public/requires/head-import.php';
        ?>



        <script type="text/javascript" src="../public/js/Ajax.js">></script>
    </head>
    <body fullbleed vertical layout unresolved>
    <template is="auto-binding" id="super-template">
        <core-drawer-panel  id="drawerPanel">
            <core-header-panel drawer>
            
                <core-toolbar class="medium">
                    <h2 id="left-title"><a href="../../">BEin3D</a></h2>
                </core-toolbar>
                <core-menu fullbleed flex>
                    <paper-shadow z="1"></paper-shadow>
                    <core-submenu icon="home" label="Home">
                        <paper-shadow z="1"></paper-shadow>
                        <core-item label="Accueil">
                            <a href="../../"></a>
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                        <core-item label="Qui sommes nous ?">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                        <core-item label="Nos produits">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                    </core-submenu>
                    <core-submenu icon="store" label="Shop">
                        <paper-shadow z="1"></paper-shadow>
                        <core-item label="La Boutique">
                            <paper-ripple fit></paper-ripple>
                            <a href="../../"></a>
                        </core-item>


                        <core-item label="Nouveautés">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                        <core-item label="Nos Makers"></core-item>
                    </core-submenu>
                    <core-submenu icon="rotation-3d" label="Design">
                        <paper-shadow z="1"></paper-shadow>
                        <core-item label="Créer mon objet"></core-item>
                        <core-item label="Topic 2"></core-item>
                    </core-submenu>
                    <core-submenu icon="payment" label="Sell">
                        <paper-shadow z="1"></paper-shadow>
                        <core-item label="Mes Objets"></core-item>
                        <core-item label="Mes Ventes"></core-item>
                    </core-submenu>
                </core-menu>
            </core-header-panel>



            
            <core-header-panel main>
                

                <core-toolbar class="medium" id="barre2">
                    <!-- TOP TOOLBAR -->
                    <core-icon-button id="navicon" icon="menu"></core-icon-button>
                    <paper-tabs flex selected="{{menu}}" valueattr="menu-cat" noink>
                        <paper-tab menu-cat="home">HOME</paper-tab>
                        <paper-tab menu-cat="shop">SHOP</paper-tab>
                        <paper-tab menu-cat="design">DESIGN</paper-tab>
                        <paper-tab menu-cat="sell">SELL</paper-tab>
                    </paper-tabs>
    <!--                <core-field>                 
                        <label></label>
                        <input placeholder="Recherche" flex>
                        <core-icon-button icon="search"></core-icon-button>
                    </core-field>-->
                    <paper-input id="search-mainpage-input" label="Rechercher"></paper-input>
                    <core-icon-button icon="search"></core-icon-button>

                    <?php include_once 'C:\wamp\www\bein3d\application\views\scripts\Panier\index.phtml'; ?>
                  
                    <paper-button  id="connexion-button" label="CONNEXION" onclick="toggleDialog('paper-dialog-transition-center')"></paper-button>
                    <paper-dialog heading="CONNEXION" transition="paper-dialog-transition-center">

                        <core-form-connexion></core-form-connexion>

                    </paper-dialog>


                    <paper-button  id="inscription-button" label="INSCRIPTION" onclick="toggleDialog('paper-dialog-transition-center')"></paper-button>
                    <paper-dialog heading="Inscription" transition="paper-dialog-transition-center">

                        <core-form-inscription>           
                        </core-form-inscription>

                    </paper-dialog><!--
                        
                    </core-pages>
                                    
                    <!--</div>-->          
                </core-toolbar>
                        <core-pages selected="{{menu}}" valueattr="menu-cat">
                            <section menu-cat="home">
                                <paper-tabs  menu-cat="home" flex selected="{{selected}}">                            
                                    <paper-tab>ACCUEIL</paper-tab>
                                    <paper-tab>QUI SOMMES NOUS</paper-tab>
                                    <paper-tab>NOS PRODUITS</paper-tab>
                                </paper-tabs>


                                <paper-footer></paper-footer>
                                </div>
                            </section>
                            <section menu-cat="shop">
                                <paper-tabs  menu-cat="shop" flex selected="{{selected}}">                            
                                    <paper-tab>LA BOUTIQUE</paper-tab>
                                    <paper-tab>NOUVEAUTES</paper-tab>
                                    <paper-tab>NOS MAKERS</paper-tab>
                                </paper-tabs>
                                <h1>Shop</h1>
                                <center><table class="catalogue" cellspacing="60">
                                        <tr>

                                            <?php
                                            $cmp = 1;
                                            //var_dump($_SESSION['nbproduit']);
                                            foreach ($this->lesProduits as $produit) {
                                                echo "<td class='produit-catalogue'>"
                                                . "<paper-shadow z='1' animated>";
                                                echo "<img src='../public/image/produits/$produit->image'>";
                                                echo "<h4>$produit->nom</h4>";
                                                //echo "<p class='nom'>";
                                                echo "<span flex><p class='prix-produit'>$produit->prixunitaire €</p>";
                                                echo "<paper-button raised role='button' class='like'>"
                                                . "<core-icon icon='favorite'></core-icon></paper-button>";
                                                echo "<paper-button raised role='button' class='add-panier' onclick='envoyerDonnees($produit->id)'>"
                                                . "<core-icon icon='add-shopping-cart'></core-icon></paper-button>";
                                                echo "</paper-shadow></td>";
                                                $cmp++;
                                                if ($cmp > 3) {
                                                    $cmp = 0;
                                                    echo"</tr><tr>";
                                                }
                                            }
                                            ?>

                                        </tr>
                                    </table></center>

                            </section>
                            <section menu-cat="design">
                                <paper-tabs  menu-cat="design" flex selected="{{selected}}">                            
                                    <paper-tab>CREER MON OBJET</paper-tab>
                                    <paper-tab>QUI SOMMES NOUS</paper-tab>
                                    <paper-tab>NOS PRODUITS</paper-tab>
                                </paper-tabs>
                                <h1>Design</h1>
                            </section>
                            <section menu-cat="sell">                   
                                <paper-tabs  menu-cat="sell" flex selected="{{selected}}">                            
                                    <paper-tab>MES OBJETS</paper-tab>
                                    <paper-tab>MES VENTES</paper-tab>
                                </paper-tabs>
                                <h1>Sell</h1>
                            </section>
                        </core-pages>

                    </core-header-panel>

                    </core-drawer-panel>
                    </template>
                    <polymer-element name="component-form" extends="form" on-submit="{{ prepareSubmit }}" on-click="{{ handleClick }}">
                        <script>
                            Polymer('component-form', {
                                handleClick: function (event, detail, sender) {
                                    if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'submit') {
                                        this.prepareSubmit();
                                        this.submit();
                                    }
                                    if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'reset') {

                                        this.form.reset();
                                    }

                                },
                                prepareSubmit: function () {
                                    Array.prototype.forEach.call(this.children, function (child) {
                                        var name = child.getAttribute('name');
                                        // Add <input type="hidden">s for all custom elements with a name and value besides submit buttons
                                        if (child.localName.indexOf('-') !== -1 && name && 'value' in child && child.getAttribute('type') !== 'submit') {
                                            element = document.createElement('input');
                                            element.setAttribute('type', 'hidden');
                                            element.setAttribute('name', name);
                                            element.setAttribute('value', child.value);
                                            this.appendChild(element);
                                        }
                                    }.bind(this));
                                },
                            });

                        </script>
                    </polymer-element>



                    </body>

                    </html>
                    <script type="text/javascript">
                    //
                    //    function addName() {
                    //        var recup = document.querySelectorAll("hello-john-doe")[0];
                    //        document.querySelector("buddies-list").buddies.push({name: recup.name});
                    //    }
                    //    ;
                        function toggleDialog(transition) {
                            var dialog = document.querySelector('paper-dialog[transition=' + transition + ']');
                            dialog.toggle();
                        }
                        ;

                        var MonTableau = new Array();


                        var scope = document.querySelector('template[is=auto-binding]');

                        scope.toggleDialog1 = function (e) {
                    //        if (e.target.localName != 'paper-button') {
                    //            return;
                    //        }
                            var d = e.target.nextElementSibling;
                            if (!d) {
                                return;
                            }
                            d.toggle();
                        };

                        var content = document.getElementById('super-template');
                        //alert(content);
                        var nav = document.getElementById('navicon');
                        //alert(nav);
                        content.addEventListerner('template-bound', function () {
                            console.log(document.query - selector('navicon'));
                        })

                    //    document.addEventListener('polymer-ready', function(){
                    //        var navicon=document.getElementById('navicon');
                    //        alert(navicon);
                    //        var drawerPanel=document.getElementById('drawerPanel');
                    //        navicon.addEventListener('click',function(){
                    //            drawerPanel.togglePanel();
                    //        });
                    //    });





                    </script>