<html>

    <?php
    include_once "../public/requires/head-import.php";
    $first = true;
    foreach ($this->news as $news) {
        if ($first) {
            print '<script>setId(' . $news["id"] . ');</script>';
            $first = false;
        }
        print '<li><span class="id">' . $news["id"] . '</span>' . $news["message"] . '<core-icon-button icon="create" onclick="champ(' . $news["id"] . ')"></core-icon-button>'
                . '<div id=' . $news["id"] . ' style="visibility : hidden"><paper-commentaire ></paper-commntaire><div></li>';
    }
    ?>


</html>
<script type="text/javascript">
    function champ(id) {
        var element = $('body /deep/ .idnew');
        
        element.attr('value',id);
        alert(element.attr('value'));
        if ($('#' + id).css('visibility') == "hidden") {
            $('#' + id).css('visibility', 'visible');
        } else {
            $('#' + id).css('visibility', 'hidden');
        }
    }
</script>
