<html>
    
<?php
require "../public/requires/head-import.php";
$first = true;
echo "<table>";
foreach ($this->news as $news) {
    if ($first) {
        print '<script>setId(' . $news["id"] . ');</script>';
        $first = false;
    }
    print '<tr><td>'
            .'<core-item><span class="id">' . $news["id"] . '</span>' . $news["message"]
            .'<core-icon-button icon="create" onclick="champ('.$news["id"] .')"></core-icon-button>'
            .'<input id='.$news["id"] .' type="hidden">'
            . '</core-item>'
            . '</td></tr>';
}
echo "</table>";
?>
    <core-ajax  id="ajax" url="http://gdata.youtube.com/feeds/api/videos/"></core-ajax>
</html>
<script type="text/javascript">
    function champ(id){
        if($("#"+id).attr('type')=="hidden"){
        $("#"+id).attr("type","text");
    }else{
        $("#"+id).attr("type","hidden");
    }
    }
    </script>
    <script>
        </script>