<html>

    <?php
    include_once "../public/requires/head-import.php";
    $first = true;
    foreach ($this->news as $news) {
        if ($first) {
            print '<script>setId(' . $news["id"] . ');</script>';
            $first = false;
        }
        print '<li><span class="id">' . $news["id"] . '</span>' . $news["message"] . '<core-icon-button icon="create" onclick="champ(' . $news["id"] . ')"></core-icon-button>'
                . '<div id=' . $news["id"] . ' style="visibility : hidden"><paper-commentaire id=' . $news["id"] . ' ></paper-commntaire><div></li>';
    }
    ?>
    <core-scroll-threshold id="threshold" lowerThreshold="500"
  on-lower-trigger="{{loadMore}}" lowerTriggered="{{news}}">
        <core-item label="{{news}}"></core-item>  
    </core-scroll-threshold>


</html>
<script>
Polymer('core-croll-threshold',{
    loadMore: function() {
  this.asyncLoadStuffThen(function() {
    this.$.threshold.clearLower();
  }.bind(this));
}

    this.news='1';
});
</script>
<script type="text/javascript">
    function champ(id) {
//        var element = $('body /deep/ .idnews');
//        
//        element.attr('value','id');
//        alert(element.attr('value'));
       // alert(document.querySelectorAll('paper-commentaire'));
        var cellules = document.querySelectorAll('paper-commentaire');
        for (var i = 0; i < cellules.length; i++) {
 
                
            cellules[i].idnew=id;
         //   alert(cellules[i].idnew);
        }

        //alert($('paper-commentaire').idnew);
        if ($('#' + id).css('visibility') == "hidden") {
            $('#' + id).css('visibility', 'visible');
        } else {
            $('#' + id).css('visibility', 'hidden');
        }
    }
</script>
