        <style shim-shadowdom>


            section {
                padding: 20px 0;
            }

            section > div {
                padding: 14px;
                font-size: 16px;
            }

            button{
                margin: 8px 4px;
            }

            html /deep/ [autofocus] {
                color: #03a9f4;
            }

            html /deep/ .scrolling::shadow #scroller {
                height: 350px;
            }

            html /deep/ .colored {
                border: 1px solid #0f9d58;
                background-color: #b7e1cd;
                color: #0f9d58;
            }

            html /deep/ .size-position {
                position: fixed;
                top: 156px;

                right: 150px;
                left: 65%;
            }

            html /deep/ .size-position::shadow #scroller {
                width: 300px;
                height: 300px;
            }

        </style>

            <!---SHOP CONTENT-->



            <h1>Mes Actus</h1>
            <ul id="actus">
                
                <?php include_once 'C:\wamp\www\bein3d\application\views\scripts\Recup\index.phtml'; ?>
                
            </ul>

    <polymer-element name="component-form" extends="form" on-submit="{{ prepareSubmit }}" on-click="{{ handleClick }}">
        <script>
            Polymer('component-form', {
                handleClick: function (event, detail, sender) {
                    if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'submit') {
                        this.prepareSubmit();
                        this.submit();
                    }
                    if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'reset') {

                        this.form.reset();
                    }

                },
                prepareSubmit: function () {
                    Array.prototype.forEach.call(this.children, function (child) {
                        var name = child.getAttribute('name');
                        // Add <input type="hidden">s for all custom elements with a name and value besides submit buttons
                        if (child.localName.indexOf('-') !== -1 && name && 'value' in child && child.getAttribute('type') !== 'submit') {
                            element = document.createElement('input');
                            element.setAttribute('type', 'hidden');
                            element.setAttribute('name', name);
                            element.setAttribute('value', child.value);
                            this.appendChild(element);
                        }
                    }.bind(this));
                },
            });

            document.addEventListener('polymer-ready', function () {
                var navicon = document.getElementById('navicon');
                var drawerPanel = document.getElementById('drawerPanel');
                navicon.addEventListener('click', function () {
                    drawerPanel.togglePanel();
                })
            })
        </script>
    </polymer-element>


<script type="text/javascript">
    $("#shop").click(function () {
        if (!$('#design-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#design-content').toggleClass("hide");
        }
        if (!$('#accueil-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#accueil-content').toggleClass("hide");
        }
        if ($('#shop-content1').hasClass("hide")) {
            $('#shop-content1').toggleClass("hide");
        }
        $('#shop-content').toggleClass("hide");



    });
    $("#design").click(function () {
        if (!$('#shop-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#shop-content').toggleClass("hide");
        }
        if (!$('#accueil-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#accueil-content').toggleClass("hide");
        }
        if ($('#shop-content1').hasClass("hide")) {
            $('#shop-content1').toggleClass("hide");
        }
        $('#design-content').toggleClass("hide");



    });
    $("#accueil").click(function () {
        if (!$('#shop-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#shop-content').toggleClass("hide");
        }
        if (!$('#shop-content1').hasClass("hide")) {
            $('#shop-content1').toggleClass("hide");
        }
        if (!$('#design-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#design-content').toggleClass("hide");
        }
        $('#accueil-content').toggleClass("hide");



    });


//
//    function addName() {
//        var recup = document.querySelectorAll("hello-john-doe")[0];
//        document.querySelector("buddies-list").buddies.push({name: recup.name});
//    }
//    ;
    function toggleDialog(transition) {
        var dialog = document.querySelector('paper-dialog[transition=' + transition + ']');
        dialog.toggle();
    }
    ;


    function recupinfo() {
        var login = document.querySelectorAll("paper-input")[1];
        document.getElementById('affiche').innerHTML = login.inputValue;

        var mdp = document.querySelectorAll("paper-input")[2];


        var Cmdp = document.querySelectorAll("paper-input")[3];
        if (mdp != Cmdp) {
            document.getElementById('affiche').innerHTML = "Veuillez confirmez votre mot de passe."
        }

        var email = document.querySelectorAll("paper-input")[4];
        document.getElementById('affiche').innerHTML = login.inputValue;
    }
    var scope = document.querySelector('template[is=auto-binding]');

    scope.toggleDialog1 = function (e) {
//        if (e.target.localName != 'paper-button') {
//            return;
//        }
        var d = e.target.nextElementSibling;
        if (!d) {
            return;
        }
        d.toggle();
    };



</script>