<?php $this->layout()->setLayout('backoffice_layout'); ?>

<p>Etes-vous sur de vouloir supprimer le client : 
    '<?php echo $this->visiteur['nom'] . " (identifiant: " . $this->visiteur['id'] . ")" ?>'
</p>
<form action="<?php echo $this->url(array('controller' => 'visiteur', 'action' => 'supprimer')); ?>" method="post">
    <div><input type="hidden" name="id" value="<?php echo $this->visiteur['id']; ?>"/>
        <input type="submit" name="supprimer" value="Oui"/>
        <input type="submit" name="supprimer" value="Non"/>
    </div>
</form>