<h1 class="profile-title">Mon profil</h1>
<div class="profile-top">
    <div class="avatarUser">
        <div class="avatar">
            <core-icon class="big" icon="social:person"></core-icon>
        </div>
        <h2> Quentin Woolys </h2>
    </div>


    <div class="collapse">
        <div class="head-collapse" onclick="document.querySelector('#collapse').toggle();">Information personnelles</div>
        <core-collapse id="collapse">
            <div class="core-form-personal-data">
                <form-profile-personal-data></form-profile-personal-data>
            </div>
        </core-collapse>
    </div>
</div>
