<html>
    <head>
        <script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
        <title>01-introduction</title>
        <!-- Load Polymer -->
        <script
            src="../components/platform/platform.js">
        </script>
        <link rel="import"
              href="../components/core-toolbar/core-toolbar.html">
        <link rel="import"
              href="../components/core-drawer-panel/core-drawer-panel.html">
        <link rel="import"
              href="../components/core-header-panel/core-header-panel.html">
        <link rel="import"
              href="../components/core-item/core-item.html">
        <link rel="import"
              href="../components/core-icons/core-icons.html">
        <link rel="import"
              href="../components/paper-icon-button/paper-icon-button.html">
        <link rel="import"
              href="../components/paper-menu-button/paper-menu-button.html">
        <link rel="import"
              href="../components/paper-item/paper-item.html">
        <link rel="import"
              href="../components/paper-tabs/paper-tabs.html">
        <link rel="import"
              href="../components/paper-input/paper-input.html">

        <link rel="import"
              href="../components/paper-dialog/paper-dialog.html">
        <link rel="import"
              href="../components/paper-button/paper-button.html">
        <link rel="import" 
              href="../components/core-icons/core-icons.html">
        <link rel="import" 
              href="../components/core-icons/social-icons.html">
        <link rel="import" 
              href="../components/core-collapse/core-collapse.html">

        <link rel="import" 
              href="../components/core-collapse/core-collapse.html">
        <link rel="import" href="../components/paper-radio-group/paper-radio-group.html">
        <link rel="import" href="../components/paper-radio-button/paper-radio-button.html">



        <!-- NEW ELEMENTS -->
        <link rel="import"
              href="../components/core-form-inscription/core-form-inscription.html">     
        <link rel="import"
              href="../components/core-form-connexion/core-form-connexion.html">
        <link rel="import"
              href="../components/core-form-personal-data/core-form-personal-data.html"> 
        <!-- STYLESHEETS -->

        <link rel="stylesheet" href="../style/CSS.css" type="text/css">
        <link rel="stylesheet" href="../style/shadow-dom.css" type="text/css">
        <!-- FONTS -->
        <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="cssSlider created with cssSlider, a free wizard program that helps you easily generate beautiful web slideshow" />


        <style shim-shadowdom>


            section {
                padding: 20px 0;
            }

            section > div {
                padding: 14px;
                font-size: 16px;
            }

            button{
                margin: 8px 4px;
            }

            html /deep/ [autofocus] {
                color: #03a9f4;
            }

            html /deep/ .scrolling::shadow #scroller {
                height: 350px;
            }

            html /deep/ .colored {
                border: 1px solid #0f9d58;
                background-color: #b7e1cd;
                color: #0f9d58;
            }

            html /deep/ .size-position {
                position: fixed;
                top: 156px;

                right: 150px;
                left: 65%;
            }

            html /deep/ .size-position::shadow #scroller {
                width: 300px;
                height: 300px;
            }

        </style>


        <!-- Ajax-form imports -->

        <script src="../../bower_components/webcomponentsjs/webcomponents.js"></script>
        <link rel="import" href="../../bower_components/ajax-form/ajax-form.html">
        <!--This is only used for mocking the HTTP requests since this demo does not have a server to handle requests.-->
        <script src="../../bower_components/ajax-form/demo_resources/sinon-server-1.10.2.js"></script>
        <link rel="import" href="../../public/components/polymer/polymer.html">

        <!-- Fin des imports -->



    </head>
    <body fullbleed vertical layout unresolved>

    <core-drawer-panel id="drawerPanel">

        <core-header-panel drawer vertical layout id="left-menu">
            <core-toolbar class="medium-tall" id="barre"><h2>BEin3D</h2></core-toolbar>
            <core-menu><!--
                -->                <core-item label="Shop"></core-item>
                <core-item label="Design"></core-item>
                <core-item label="Sell"></core-item><!--
                -->            </core-menu>
        </core-header-panel>

        <core-header-panel main >
            <core-toolbar class="medium-tall" id="barre2">
                <!-- TOP TOOLBAR -->
                <core-icon-button id="navicon" icon="menu" on-tap="{{menuAction}}"></core-icon-button>
                <paper-tabs flex selected="{{selected}}">
                    <paper-tab id="shop">SHOP</paper-tab>
                    <paper-tab id="design">DESIGN</paper-tab>
                    <paper-tab>SELL</paper-tab>
                </paper-tabs>
                <paper-input id="search-mainpage-input" label="Rechercher"></paper-input>
                <paper-icon-button icon="search"></paper-icon-button>
                <?php
                echo $this->Login;
                ?>
                <!--
                <!-- BOTTOM TOOLBAR -->

                <!--<div class="bottom" id="sous-menu"> -->

                <paper-tabs class="bottom" flex selected="{{selected}}">
                    <paper-tab>+POPULAIRES</paper-tab>
                    <paper-tab>NOUVEAUTES</paper-tab>
                    <paper-tab>ART</paper-tab>
                    <paper-tab>MEILLEURS MAKERS</paper-tab>
                    <paper-tab>CONCOURS</paper-tab>
                </paper-tabs>                

            </core-toolbar>


            <div id="connect" class="profil">
                <h1>Mon profil</h1>
                <div class="profil-top">
                    <div class="avatarUser">
                        <div class="avatar">
                            <core-icon class="big" icon="social:person"></core-icon>
                        </div>
                        <h2> Quentin Woolys </h2>
                    </div>


                    <div class="collapse">
                        <div class="head-collapse" onclick="document.querySelector('#collapse').toggle();">Information personnelles</div>
                        <core-collapse id="collapse">
                            <p><?php var_dump($this->name); ?></p>
                            <p><?php var_dump($this->sexe); ?></p>
                            <p><?php var_dump($this->error); ?></p>
                            <div class="core-form-personal-data">
                                <core-form-personal-data></core-form-personal-data>


                                <!-- Test de l'ajax form -->

                                <div>
                                    <div id="content">
                                        <form is="ajax-form" action="http://localhost/bein3d/public/profil/index" method="post">
                                            <div>
                                                <paper-input name='name'></paper-input>
                                            </div>

                                            <div>
                                                <label>Address: <input type="text" name="address" required></label>
                                            </div>

                                            <div>
                                                <label>Favorite color: <input type="text" name="color"></label>
                                            </div>

                                            <div>
                                                <b>Receive periodic email updates from us?</b>
                                                <input type="radio" name="emailCommunication" value="yes" checked>yes
                                                <input type="radio" name="emailCommunication" value="no">no

                                                <paper-radio-group name='sexe'>
                                                    <paper-radio-button name='femme' value='0' ></paper-radio-button>
                                                    <paper-radio-button name='homme' value='1' ></paper-radio-button>
                                                </paper-radio-group>

                                            </div>

                                            <input type="submit">
                                        </form>
                                    </div>

                                </div>

                                <!-- fin test -->

                        </core-collapse>
                    </div>
                </div>



            </div>
            <div id="shop-content" class="hide">
                <table>
                    <tr> 
                        <?php
                        for ($i = 0; $i < 100; $i++) {
                            echo "<td>";
                            echo "<div id='produit'>adazdaz</div>";
                            echo "</td>";
                        }
                        ?>
                    </tr>
                </table>
            </div>
            <div id="design-content" class="hide">
                <center> ntm
                </center>

            </div>
        </core-header-panel>

    </core-drawer-panel>



    <polymer-element name="component-form" extends="form" on-submit="{{ prepareSubmit }}" on-click="{{ handleClick }}">

        <script>
            Polymer('component-form', {
                handleClick: function (event, detail, sender) {
                    if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'submit') {
                        this.prepareSubmit();
                        this.prepareSubmitDeux();
                        this.submit();
                    }
                    if (event.target.localName.indexOf('-') !== -1 && event.target.getAttribute('type') === 'reset') {

                        this.form.reset();
                    }

                },
                prepareSubmit: function () {
//                    var femme = $('#femme').val();
//                    var homme = $('#homme').val();
//                    if (femme === '' || homme === '') {
//                        alert('les champs doivent être remplis');
//                    } else {
//                        $.ajax({
//                            url: $this.attr('Profil'),
//                            type: $this.attr('post'),
//                            data: $this.serialize(),
//                            success: function(html) {
//                                alert(html);
//                            }
//                            
//                        })
//                    };



                    Array.prototype.forEach.call(this.children, function (child) {


//                        var shadowhost = document.getElementById('ShadowHost');
//                        var shadowroot = new WebKitShadowRoot(shadowhost);
//                        console.log(shadowroot);
//                        if (name && name.val() === 'sexe') {
//
//                            element = document.createElement('input');
//                            element.setAttribute('type', 'hidden');
//                            element.setAttribute('name', name);
//                            element.setAttribute('value', choix);
//                            this.appendChild(element);
//
//                        }
                        var name = child.getAttribute('name');
                        // Add <input type="hidden">s for all custom elements with a name and value besides submit buttons
                        if (child.localName.indexOf('-') !== -1 && name && 'value' in child && child.getAttribute('type') !== 'submit') {
                            element = document.createElement('input');
                            element.setAttribute('type', 'hidden');
                            element.setAttribute('name', name);
                            element.setAttribute('value', child.value);
                            this.appendChild(element);
                        }
                    }.bind(this));
                },
                prepareSubmitDeux: function () {

                    var radioButtonTab = document.querySelectorAll('html /deep/ paper-radio-button');
                    var choix = [];

                    for (i = 0; i < radioButtonTab.length; ++i) {
                        choix[i] = radioButtonTab[i].id;
                    }
                    alert(choix[1]);
                    $.ajax({
                        type: "POST",
                        data: {femme: choix[0], homme: choix[1]},
                        url: "http://localhost/bein3d/public/profil/index",
                        success: function (msg) {
                            $('.answer').html(msg);
                            alert('9a marche !');
                        }
                    });


                },
            });
        </script>
    </polymer-element>




</body>

<!-- Script de l'ajax-form -->

<script>
    (function () {
        var form = document.querySelectorAll('form')[0],
                content = document.getElementById('content');
        form.addEventListener('invalid', function () {
            alertify.error('Some form fields are invalid!');
        });
        form.addEventListener('submitting', function (event) {
            document.getElementById('pleaseWait').className = '';
            content.className = 'hidden';
            event.detail.raytest = 'foobar';
            event.detail.color = 'blue';
        });
        form.addEventListener('submitted', function (event) {
            document.getElementById('pleaseWait').className = 'hidden';
            content.className = '';
            if (event.detail.status > 299) {
                alertify.error('Submission failed!  Please try again.')
            }
            else {
                content.innerHTML = 'Thanks!  Your choices have been submitted!';
            }
        });
    }());
</script>

<script>
    // This code is only used to mock/intercept HTTP requests associated
    // with the form submit.  This is needed since the demo doesn't have
    // a server to handle these requests.
    (function () {
        sinon.FakeXMLHttpRequest.useFilters = true;
        sinon.FakeXMLHttpRequest.addFilter(function (method, url) {
            return !(/test/).test(url);
        });
        var server = sinon.fakeServer.create();
        server.respondWith([200, {}, '']);
        server.autoRespond = true;
        server.autoRespondAfter = 5000;
    }());
</script>

<!-- Fin du script -->


</html>
<script type="text/javascript">
    $("#shop").click(function () {
        if (!$('#design-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#design-content').toggleClass("hide");
        }
        if (!$('#connect').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#connect').toggleClass("hide");
        }

        $('#shop-content').toggleClass("hide");



    });
    $("#design").click(function () {
        if (!$('#shop-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#shop-content').toggleClass("hide");
        }
        if (!$('#connect').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#connect').toggleClass("hide");
        }
        $('#design-content').toggleClass("hide");



    });

//
//    function addName() {
//        var recup = document.querySelectorAll("hello-john-doe")[0];
//        document.querySelector("buddies-list").buddies.push({name: recup.name});
//    }
//    ;
    function toggleDialog(transition) {
        var dialog = document.querySelector('paper-dialog[transition=' + transition + ']');
        dialog.toggle();
    }
    ;


    function recupinfo() {
        var name = document.querySelectorAll("paper-input")[1];
        document.getElementById('affiche').innerHTML = login.inputValue;

        var fname = document.querySelectorAll("paper-input")[2];
        if (fname === null) {
            console.log(fname);
            document.getElementById('affiche').innerHTML = "Les champs doivent etre rempli !"
        }

        var adress = document.querySelectorAll("paper-input")[3];
    }
    var scope = document.querySelector('template[is=auto-binding]');

    scope.toggleDialog1 = function (e) {
//        if (e.target.localName != 'paper-button') {
//            return;
//        }
        var d = e.target.nextElementSibling;
        if (!d) {
            return;
        }
        d.toggle();
    };




</script>