<html>
    <head>
        <title>Profil</title>
        <!-- Load Polymer -->
        <script
            src="../components/platform/platform.js">
        </script>
        <script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
        <link rel="import" 
              href="../components/polymer/polymer.html">
        <link rel="import"
              href="../components/core-toolbar/core-toolbar.html">
        <link rel="import"
              href="../components/core-drawer-panel/core-drawer-panel.html">
        <link rel="import"
              href="../components/core-header-panel/core-header-panel.html">
        <link rel="import"
              href="../components/core-item/core-item.html">
        <link rel="import"
              href="../components/core-icons/core-icons.html">
        <link rel="import"
              href="../components/paper-icon-button/paper-icon-button.html">
        <link rel="import"
              href="../components/paper-menu-button/paper-menu-button.html">
        <link rel="import"
              href="../components/paper-item/paper-item.html">
        <link rel="import"
              href="../components/paper-tabs/paper-tabs.html">
        <link rel="import"
              href="../components/paper-input/paper-input.html">

        <link rel="import"
              href="../components/paper-dialog/paper-dialog.html">
        <link rel="import"
              href="../components/paper-button/paper-button.html">
        <link rel="import" 
              href="../components/core-icons/core-icons.html">
        <link rel="import" 
              href="../components/core-icons/social-icons.html">
        <link rel="import" 
              href="../components/core-collapse/core-collapse.html">

        <link rel="import" 
              href="../components/core-collapse/core-collapse.html">
        <link rel="import" href="../components/paper-radio-group/paper-radio-group.html">
        <link rel="import" href="../components/paper-radio-button/paper-radio-button.html">



        <!-- NEW ELEMENTS -->
        <link rel="import"
              href="../components/core-form-inscription/core-form-inscription.html">     
        <link rel="import"
              href="../components/core-form-connexion/core-form-connexion.html">
        <link rel="import"
              href="../components/core-form-personal-data/core-form-personal-data.html"> 
        <link rel="import"
              href="../components/form-profile-personal-data/form-profile-personal-data.html"> 
        <!-- STYLESHEETS -->

        <link rel="stylesheet" href="../style/CSS.css" type="text/css">
        <link rel="stylesheet" href="../style/shadow-dom.css" type="text/css">
        <!-- FONTS -->
        <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="cssSlider created with cssSlider, a free wizard program that helps you easily generate beautiful web slideshow" />


        <style shim-shadowdom>


            section {
                padding: 20px 0;
            }

            section > div {
                padding: 14px;
                font-size: 16px;
            }

            button{
                margin: 8px 4px;
            }

            html /deep/ [autofocus] {
                color: #03a9f4;
            }

            html /deep/ .scrolling::shadow #scroller {
                height: 350px;
            }

            html /deep/ .colored {
                border: 1px solid #0f9d58;
                background-color: #b7e1cd;
                color: #0f9d58;
            }

            html /deep/ .size-position {
                position: fixed;
                top: 156px;

                right: 150px;
                left: 65%;
            }

            html /deep/ .size-position::shadow #scroller {
                width: 300px;
                height: 300px;
            }

        </style>


        <!-- Ajax-form imports -->

<!--        <script src="../components/webcomponentsjs/webcomponents.js"></script>
        <link rel="import" href="../components/ajax-form/ajax-form.html">-->

        <!-- Fin des imports Ajax-form -->



    </head>
    <body fullbleed vertical layout unresolved>

    <core-drawer-panel id="drawerPanel">

        <core-header-panel drawer vertical layout id="left-menu">
            <core-toolbar class="medium-tall" id="barre"><h2>BEin3D</h2></core-toolbar>
            <core-menu><!--
                -->                <core-item label="Shop"></core-item>
                <core-item label="Design"></core-item>
                <core-item label="Sell"></core-item><!--
                -->            </core-menu>
        </core-header-panel>

        <core-header-panel main >
            <core-toolbar class="medium-tall" id="barre2">
                <!-- TOP TOOLBAR -->
                <core-icon-button id="navicon" icon="menu" on-tap="{{menuAction}}"></core-icon-button>
                <paper-tabs flex selected="{{selected}}">
                    <paper-tab id="shop">SHOP</paper-tab>
                    <paper-tab id="design">DESIGN</paper-tab>
                    <paper-tab>SELL</paper-tab>
                </paper-tabs>
                <paper-input id="search-mainpage-input" label="Rechercher"></paper-input>
                <paper-icon-button icon="search"></paper-icon-button>
                <?php
                echo $this->Login;
                ?>
                <!--
                <!-- BOTTOM TOOLBAR -->

                <!--<div class="bottom" id="sous-menu"> -->

                <paper-tabs class="bottom" flex selected="{{selected}}">
                    <paper-tab>+POPULAIRES</paper-tab>
                    <paper-tab>NOUVEAUTES</paper-tab>
                    <paper-tab>ART</paper-tab>
                    <paper-tab>MEILLEURS MAKERS</paper-tab>
                    <paper-tab>CONCOURS</paper-tab>
                </paper-tabs>                

            </core-toolbar>


            <div id="connect" class="profil">
                <h1>Mon profil</h1>
                <div class="profil-top">
                    <div class="avatarUser">
                        <div class="avatar">
                            <core-icon class="big" icon="social:person"></core-icon>
                        </div>
                        <h2> Quentin Woolys </h2>
                    </div>


                    <div class="collapse">
                        <div class="head-collapse" onclick="document.querySelector('#collapse').toggle();">Information personnelles</div>
                        <core-collapse id="collapse">
                            <div class="core-form-personal-data">
<!--                                <core-form-personal-data></core-form-personal-data>-->


                                <!-- Ajax form -->
                                <!--                                <div>
                                                                    <div id="content">
                                                                        <form is="ajax-form" action="#" method="post">
                                                                            <div id='infoPerso'>
                                                                                <paper-input floatingLabel name="nom" label="Nom"></paper-input>
                                                                                <paper-input floatingLabel name="prenom" label="Prénom"></paper-input>
                                                                                <paper-input floatingLabel name=email label="Adresse Email"></paper-input>
                                                                                <paper-input floatingLabel name="adresse" label="Adresse"></paper-input>
                                                                                <paper-input floatingLabel name="ville" label="ville"></paper-input>
                                                                                <paper-input floatingLabel name="cp" label="Code Postal"></paper-input>
                                                                            </div>
                                                                            <input type="submit">
                                                                            <paper-button class="colored" type="submit" label='OK' onClick="submitForm()">
                                                                                <core-icon icon='check'> 
                                                                                </core-icon>
                                                                            </paper-button>
                                                                        </form>
                                                                    </div>
                                
                                                                </div>-->

                                <!-- fin ajax-form -->
                                <form-profile-personal-data></form-profile-personal-data>
                            </div>
                        </core-collapse>
                    </div>
                </div>



            </div>
            <div id="shop-content" class="hide">
                <table>
                    <tr> 
                        <?php
                        for ($i = 0; $i < 100; $i++) {
                            echo "<td>";
                            echo "<div id='produit'>adazdaz</div>";
                            echo "</td>";
                        }
                        ?>
                    </tr>
                </table>
            </div>
            <div id="design-content" class="hide">
                <center> ntm
                </center>

            </div>
        </core-header-panel>

    </core-drawer-panel>

</body>

<!-- Script de l'ajax-form -->

<!--<script>
    (function () {
        var form = document.querySelectorAll('form')[0],
                content = document.getElementById('content');
        form.addEventListener('invalid', function () {
            alertify.error('Some form fields are invalid!');
        });
        form.addEventListener('submitting', function (event) {
            content.className = 'hidden';
            event.detail.raytest = 'foobar';
            event.detail.color = 'blue';
        });
        form.addEventListener('submitted', function (event) {
            content.className = '';
            if (event.detail.status > 299) {
                alertify.error('Submission failed!  Please try again.')
            }
            else {
                //je récupère la valeur du paper input d'id nomUser
                var infoPerso = $('#infoPerso');
                var nom = infoPerso.children()[0].value;
                var prenom = infoPerso.children()[1].value;
                var email = infoPerso.children()[2].value;
                var adresse = infoPerso.children()[3].value;
                var ville = infoPerso.children()[4].value;
                var cp = infoPerso.children()[5].value;
                $.ajax({
                    url: 'http://localhost/bein3d/public/profil/formdata',
                    type: 'POST', // Le type de la requête HTTP, ici devenu POST
                    dataType: 'html',
                    data: 'nom=' + nom + '&prenom=' + prenom + '&email=' + email + '&adresse=' + adresse + '&ville=' + ville + '&cp=' + cp,
                    success: function (result)//retour de requête
                    {
                        alert("Vos informations ont bien été mises à jour");
                    }
                });
            }
        });
    }());</script>-->



</html>
<script type="text/javascript">
    $("#shop").click(function () {
        if (!$('#design-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#design-content').toggleClass("hide");
        }
        if (!$('#connect').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#connect').toggleClass("hide");
        }

        $('#shop-content').toggleClass("hide");



    });
    $("#design").click(function () {
        if (!$('#shop-content').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#shop-content').toggleClass("hide");
        }
        if (!$('#connect').hasClass('hide')) { // it checks if mobile_billing is not open
            $('#connect').toggleClass("hide");
        }
        $('#design-content').toggleClass("hide");



    });

    function toggleDialog(transition) {
        var dialog = document.querySelector('paper-dialog[transition=' + transition + ']');
        dialog.toggle();
    }
    ;

    var scope = document.querySelector('template[is=auto-binding]');

    scope.toggleDialog1 = function (e) {
//        if (e.target.localName != 'paper-button') {
//            return;
//        }
        var d = e.target.nextElementSibling;
        if (!d) {
            return;
        }
        d.toggle();
    };




</script>