<?php

echo "<paper-icon-button icon='shopping-cart' on-tap='{{toggleDialog1}}'></paper-icon-button>";
echo "<paper-dialog  class='size-position'  >";

if (isset($_SESSION['nbproduit'])) {
    foreach ($_SESSION['nbproduit'] as $key => $prod) {
//                              var_dump($prod);
        echo "<core-icon-button icon='cancel' onclick='alert()'></core-icon-button>";
        echo $prod['nom'] . "<paper-icon-button icon='remove-circle' onclick='quantite(".$prod['id'].")'></paper-icon-button>
                                  <input type='text'  id='".$prod['id']."' value='" . $prod['quantite'] . "' size='1'>
                                 <paper-icon-button icon='add-circle' ></paper-icon-button></br>";
    }
}

echo"  </paper-dialog>";
if (isset($_SESSION['nbproduit'])) {
    $nbpanier = count($_SESSION['nbproduit']);
    echo "(" . $nbpanier . ")";
}
?>
<script type="text/javascript">
    function quantite(choix) {
        
        var nb = $(#choix).value;
            $(#choix).value=nb+1;
    }
    ;

</script>
