<html>

    <body>


    <paper-icon-button icon='shopping-cart' on-tap='{{toggleDialog1}}'></paper-icon-button>
    <paper-dialog  class='size-position'  > 

        <?php
        $nbpanier = 0;
        $prixtotal = 0;
        echo "<div id='cart'>";


        Zend_Session::start();



        if (isset($_SESSION['nbproduit'])) {
            if (count($_SESSION['nbproduit']) != 0) {

                echo "<core-item center-center>Panier</core-item>";
                foreach ($_SESSION['nbproduit'] as $key => $prod) {
                    $prixtotal+=$prod['prix'] * $prod['quantite'];
                    $nbpanier += $prod['quantite'];
//                              var_dump($prod);
                    echo "<core-item class='produit-panier' vertical>";
                    echo "<core-item>"
                            .$prod['nom']
                            . "<div flex></div>"
                            . "<core-icon-button icon='close' float='right' onclick='supDonnees(" . $prod['id'] . "," . $prod['quantite'] . ")'>"                  
                            . "</core-icon-button>"
                            . "</core-item>";
                    echo " <core-item><paper-button name='moins' class='sup' onclick='quantitemoins(" . $prod['id'] . ")'>"
                        . "<core-icon icon='remove'></core-icon></paper-button>"
                                  ."<input type='text'  id='" . $prod['id'] . "' value='" . $prod['quantite'] . "' size='1'>
            <paper-button name='plus' onclick='quantiteplus(" . $prod['id'] . ")'>"
                            . "<core-icon icon='add'></core-icon></paper-button>";
                    echo $prod['prix'] . "</core-item></core-item>";
                }
                echo "<core-item>Prix total :</td><td>" . $prixtotal . "</core-item>";
            } else {
                echo "Votre panier est vide,veuillez le remplir.";
            }
        } else {
            echo "Votre panier est vide,veuillez le remplir.";
        }



        echo"  </div>";
        echo"  </paper-dialog>";




        echo "<input type='hidden' id='nbpanier' value=" . $nbpanier . ">";
        echo "<div id='nbpaniervue'>(" . $nbpanier . ") </div>";
        ?>


    </body>


</html>


