<html>
    <script type=text/javascript src="../../public/js/panier.js"></script>
    <body>
    
    
    <paper-icon-button icon='shopping-cart' on-tap='{{toggleDialog1}}'></paper-icon-button>
    <paper-dialog  class='size-position'  > 
        <?php
        $nbpanier = 0;
        echo "<div id='cart'>";


        Zend_Session::start();




        if (isset($_SESSION['nbproduit'])) {
            foreach ($_SESSION['nbproduit'] as $key => $prod) {
                 $nbpanier += $prod['quantite'];
//                              var_dump($prod);
                echo "<core-icon-button icon='cancel' onclick='supDonnees(" . $prod['id'] . ",".$prod['quantite'].")'></core-icon-button>";
                echo $prod['nom'] . "     <paper-icon-button name='moins' class='sup' icon='remove-circle' onclick='quantitemoins(" . $prod['id'] . ")'></paper-icon-button>
                                  <input type='text'  id='" . $prod['id'] . "' value='" . $prod['quantite'] . "' size='1'>
                                 <paper-icon-button name='plus' icon='add-circle'  onclick='quantiteplus(" . $prod['id'] . ")'></paper-icon-button></br>";
            }
        }


        echo"  </div>";
        echo"  </paper-dialog>";
        
        


        echo "<input type='hidden' id='nbpanier' value=" . $nbpanier . ">";
        echo "<div id='nbpaniervue'>(" . $nbpanier . ") </div>";
        ?>


    </body>
    

</html>


