<script>
    $(document).ready(function(){
                var tmp=document.querySelector('#super-template');
                tmp.menu='shop';
                tmp.sub='boutique';             
            });
</script>
<div class="contenu">
    <h3>La Boutique</h3>
    
    <table class="catalogue" cellspacing="60">
        <tr>
            <?php
            $cmp = 1;
            foreach ($this->lesProduits as $produit) {
            ?>
                <td class='produit-catalogue'>
                    <paper-shadow z='1' animated>
                    <img src='../../public/images/produits/<?php echo $produit['image']?>'>
                    <h4><?php echo $produit['nom'];?></h4>
                    <p class='nom'>
                    <span flex><p class='prix-produit'><?php echo $produit['prixunitaire']?> €</p>
                    <paper-button raised role='button' class='like' style="width: 30px;">
                    <core-icon icon='favorite'></core-icon></paper-button>
                    <paper-button raised role='button' class='add-panier'>
                    <core-icon icon='add-shopping-cart'></core-icon></paper-button>
                    </paper-shadow></td>
            <?php              
                $cmp++;
                if ($cmp > 3) {
                    $cmp = 1;
                    echo"</tr><tr>";
                }
            }
            ?>
        </tr>
    </table>
</div>
