<script>
    $(document).ready(function(){
                var tmp=document.querySelector('#super-template');
                tmp.menu='shop';
                tmp.sub='boutique';             
            });
</script>
<div class="contenu">
    <h3>La Boutique</h3>
    
   <table class="catalogue" cellspacing="60">
                                <tr>

                                    <?php
                                    Zend_Session::start();
                                    $cmp = 1;
                                    //var_dump($_SESSION['nbproduit']);
                                    foreach ($this->lesProduits as $produit) {
                                        echo "<td class='produit-catalogue'>"
                                        . "<paper-shadow z='1' animated>";
                                        echo "<img src='../../public/images/produits/$produit->image'>";
                                        echo "<h4>$produit->nom</h4>";
                                        //echo "<p class='nom'>";
                                        echo "<span flex><p class='prix-produit'>$produit->prixunitaire €</p>";
                                        echo "<paper-button raised role='button' class='like'>"
                                        . "<core-icon icon='favorite'></core-icon></paper-button>";
                                        echo "<paper-button raised role='button' class='add-panier' onclick='envoyerDonnees($produit->id)'>"
                                        . "<core-icon icon='add-shopping-cart'></core-icon></paper-button>";
                                        echo "</paper-shadow></td>";
                                        $cmp++;
                                        if ($cmp > 3) {
                                            $cmp = 0;
                                            echo"</tr><tr>";
                                        }

            
           
          

                                    }
                                    ?>

                                </tr>
                            </table>
</div>
