<?php echo $this->doctype() ?>
<html>
    <head>
        <?php
        require '../public/requires/head-import.php';
        ?>
        <script type="text/javascript" src="../public/js/Ajax.js">></script>
    </head>
    <body fullbleed vertical layout unresolved>
        
        
    <template is="auto-binding" id="super-template">
        <script>
    document.addEventListener('polymer-ready', function(){
        alert ('yolo');
        var tmp=document.querySelector('#super-template');
        var navicon=tmp.getElementById('navicon');
        alert(navicon);
        var drawerPanel=document.getElementById('drawerPanel');
        navicon.addEventListener('click',function(){
            drawerPanel.togglePanel();
        });
    });  
            
        </script>
        <core-drawer-panel  id="drawerPanel">
            <!--DRAWER-->
            <core-header-panel drawer>
                <core-toolbar class="medium">
                    <h2 id="left-title">
                        <a href="<?php
                            echo $this->url(array('controller' => 'Index',
                                'action' => 'index'))?>">BEin3D</a>
                    </h2>
                </core-toolbar>
                <core-menu fullbleed flex selected="{{menu}}" valueattr="menu-cat">
                    <core-submenu icon="home" label="Home" menu-cat="home" selected="{{sub}}" valueattr="menu-sub">
                        <paper-shadow z="1"></paper-shadow>
                        <core-item label="Accueil" menu-sub="accueil">
                            <a href="../"></a>
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                        <core-item label="Qui sommes nous ?" menu-sub="qsn">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                        <core-item label="Nos produits" menu-sub="nosproduits">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                    </core-submenu>
                    <core-submenu icon="store" label="Shop" menu-cat="shop" selected="{{sub}}" valueattr="menu-sub">
                        <paper-shadow z="1"></paper-shadow>
                        <core-item label="La Boutique" menu-sub="boutique">
                            <paper-ripple fit></paper-ripple>
                            <a href="../../"></a>
                        </core-item>
                        <core-item label="Nouveautés" menu-sub="nouveautes">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                        <core-item label="Nos Makers" menu-sub="makers">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                        
                    </core-submenu>
                    <core-submenu icon="rotation-3d" label="Design" menu-cat="design" selected="{{sub}}" valueattr="menu-sub">
                        <paper-shadow z="1"></paper-shadow>
                        <core-item label="Créer mon objet" menu-sub="creer">
                            <paper-ripple fit></paper-ripple>
                        </core-item>                        
                        <core-item label="Didacticiel" menu-sub="didacticiel">
                            <paper-ripple fit></paper-ripple>
                        </core-item>                       
                        <core-item label="Importer un modèle" menu-sub="import">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                    </core-submenu>
                    <core-submenu icon="payment" label="Sell" menu-cat="sell"selected="{{sub}}" valueattr="menu-sub">
                        <paper-shadow z="1"></paper-shadow>
                        <core-item label="Mes Objets" menu-sub="mesobjets">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                        <core-item label="Mes Ventes" menu-sub="mesventes">
                            <paper-ripple fit></paper-ripple>
                        </core-item>
                    </core-submenu>
                </core-menu>
                <div id='divfoot' flex></div>
                <footer flex>Footer</footer>
            </core-header-panel>

            <!-- MAIN -->
            <core-header-panel main >

                <core-toolbar class="medium" id="barre2">
                    <!-- TOP TOOLBAR -->
                    <core-icon-button id="navicon" icon="menu"></core-icon-button>
                    <paper-tabs flex selected="{{menu}}" valueattr="menu-cat" link noink noslide>
                        <paper-tab menu-cat="home">
                            <a href="<?php
                                echo $this->url(array('controller' => 'Index',
                                    'action' => 'index'))?>" horizontal center-center layout>HOME</a>
                        </paper-tab>
                        <paper-tab menu-cat="shop">
                            <a href="<?php
                                echo $this->url(array('controller' => 'Shop',
                                    'action' => 'boutique'))?>"horizontal center-center layout>SHOP</a>
                        </paper-tab>
                        <paper-tab menu-cat="design"><a href="<?php
                                echo $this->url(array('controller' => 'Design',
                                    'action' => 'creer'))?>"horizontal center-center layout>DESIGN</a>
                        </paper-tab>
                        <paper-tab menu-cat="sell"><a href="<?php
                                echo $this->url(array('controller' => 'Sell',
                                    'action' => 'mesobjets'))?>"horizontal center-center layout>SELL</a>
                        </paper-tab>
                    </paper-tabs>
    <!--                <core-field>                 
                        <label></label>
                        <input placeholder="Recherche" flex>
                        <core-icon-button icon="search"></core-icon-button>
                    </core-field>-->
                    <paper-input id="search-mainpage-input" label="Rechercher"></paper-input>
                    <core-icon-button icon="search"></core-icon-button>

                    <?php include_once 'C:\wamp\www\bein3d\application\views\scripts\Panier\index.phtml'; ?>
                    <input type="hidden" id="nbproduit" value="0"><p id="panier"></p>
                    <paper-button  id="connexion-button" label="CONNEXION" onclick="toggleDialog('paper-dialog-transition-center')"></paper-button>
                    <paper-dialog heading="CONNEXION" transition="paper-dialog-transition-center">

                        <core-form-connexion></core-form-connexion>

                    </paper-dialog>


                    <paper-button  id="inscription-button" label="INSCRIPTION" onclick="toggleDialog('paper-dialog-transition-center')"></paper-button>
                    <paper-dialog heading="Inscription" transition="paper-dialog-transition-center">

                        <core-form-inscription>           
                        </core-form-inscription>

                    </paper-dialog><!--
                        
                    </core-pages>
                                    
                    <!--</div>-->          
                </core-toolbar>
                <core-pages selected="{{menu}}" valueattr="menu-cat">
                    <section menu-cat="home">
                        <paper-tabs flex selected="{{sub}}" valueattr="menu-sub" noslide>                            
                            <paper-tab menu-sub="accueil">
                                <a href="<?php
                                echo $this->url(array('controller' => 'Index',
                                    'action' => 'index'))?>" horizontal center-center layout>ACCUEIL</a>
                            </paper-tab>
                            <paper-tab menu-sub="qsn">
                                <a href="<?php
                                echo $this->url(array('controller' => 'Index',
                                    'action' => 'qsn'))?>" horizontal center-center layout>QUI SOMMES NOUS</a>
                            </paper-tab>
                            <paper-tab menu-sub="nosproduits">
                                <a href="<?php
                                echo $this->url(array('controller' => 'Index',
                                    'action' => 'nosproduits'))?>" horizontal center-center layout>NOS PRODUITS</a>
                            </paper-tab>
                        </paper-tabs>
                        
                    </section>

                    <section menu-cat="shop">
                        <paper-tabs flex selected="{{sub}}" valueattr="menu-sub">                            
                            <paper-tab menu-sub="boutique">
                                <a href="<?php
                                echo $this->url(array('controller' => 'Shop',
                                    'action' => 'boutique'))?>" horizontal center-center layout>LA BOUTIQUE</a>
                            </paper-tab>
                            <paper-tab menu-sub="nouveautes">
                                <a href="<?php
                                echo $this->url(array('controller' => 'Shop',
                                    'action' => 'nouveautes'))?>" horizontal center-center layout>NOUVEAUTES</a>
                            </paper-tab>
                            <paper-tab menu-sub="makers">
                                <a href="<?php
                                echo $this->url(array('controller' => 'Shop',
                                    'action' => 'makers'))?>" horizontal center-center layout>NOS MAKERS</a>
                            </paper-tab>
                        </paper-tabs>
                    </section>
                    <section menu-cat="design">
                        <paper-tabs flex selected="{{sub}}" valueattr="menu-sub" noslide>                            
                            <paper-tab menu-sub="creer">
                                <a href="<?php
                                echo $this->url(array('controller' => 'Design',
                                    'action' => 'creer'))?>" horizontal center-center layout>CREER MON OBJET</a>
                            </paper-tab>
                            <paper-tab menu-sub="didacticiel">
                                <a href="<?php
                                echo $this->url(array('controller' => 'Design',
                                    'action' => 'didact'))?>" horizontal center-center layout>DIDACTITIEL</a>
                            </paper-tab>
                            <paper-tab menu-sub="import">
                                <a href="<?php
                                echo $this->url(array('controller' => 'Design',
                                    'action' => 'importer'))?>" horizontal center-center layout>IMPORTER UN MODELE</a>
                            </paper-tab>
                        </paper-tabs>
                    </section>
                    <section menu-cat="sell">                   
                        <paper-tabs flex selected="{{sub}}" valueattr="menu-sub" noslide>                            
                            <paper-tab menu-sub="mesobjets">MES OBJETS</paper-tab>
                            <paper-tab menu-sub="mesventes">MES VENTES</paper-tab>
                        </paper-tabs>
                    </section>
                </core-pages>               
                <?php                
                    echo $this->layout()->content;
                ?>  
            </core-header-panel>

        </core-drawer-panel>
    </template>
</body>

</html>