<?php echo $this->doctype() ?>
<html>
     
    <head>
        <style shim-shadowdom>
            html /deep/ [autofocus] {
                color: #03a9f4;
            }

            html /deep/ .scrolling::shadow #scroller {
                height: 350px;
            }

            html /deep/ .colored {
                border: 1px solid #0f9d58;
                background-color: #b7e1cd;
                color: #0f9d58;
            }

            html /deep/ .size-position {
                position: fixed;
                top: 156px;

                right: 150px;
                left: 65%;
            }

            
            html /deep/ .size-position::shadow #scroller {
                width: 300px;
                height: 300px;
            }

            // fin toogle


            html paper-tabs /deep/ .pink::shadow #selectionBar {
                background-color: red;
            }
        </style>
        <?php
        require '../public/requires/head-import.php';
        ?>

    </head>
    <body fullbleed vertical layout unresolved>
        <input type="hidden" value="<?php echo $this->layout()->menu ?>" id="chemin">
        
        <script>
            document.addEventListener('polymer-ready', function () {
                var action='<?php echo Zend_Controller_Front::getInstance()->getRequest()->getActionName() ?>';
                document.querySelector('menu-toolbar-hsds').menu = '<?php echo $this->layout()->menu ?>';
                document.querySelector('menu-toolbar-hsds').chemin = '<?php echo $this->layout()->chemin ?>';
                document.querySelector('menu-drawer-hsds').menu = '<?php echo $this->layout()->menu ?>';
                document.querySelector('menu-drawer-hsds').chemin = '<?php echo $this->layout()->chemin ?>';
                document.querySelector('menu-drawer-hsds').menusub = action;
                document.querySelector('submenu-mainpage').menu = '<?php echo $this->layout()->menu ?>';
                document.querySelector('submenu-mainpage').chemin = '<?php echo $this->layout()->chemin ?>';
                document.querySelector('submenu-mainpage').menusub =action;
                        

                var navicon = document.getElementById('navicon');
                var drawerPanel = document.getElementById('drawerPanel');
                navicon.addEventListener('click', function () {
                    drawerPanel.togglePanel();
                });

            });

        </script>

    <core-drawer-panel  id="drawerPanel">
        <!--DRAWER-->
        <core-header-panel drawer>
            <core-toolbar class="medium">
                <h2 id="left-title">

                    <a href="<?php
                    echo $this->url(array('controller' => 'Index',
                        'action' => 'index'))
                    ?>">BEin3D</a>
                </h2>
            </core-toolbar>
            <menu-drawer-hsds></menu-drawer-hsds>

            <div id='divfoot' flex></div>
            <footer flex>Footer</footer>
        </core-header-panel>

        <!-- MAIN -->
        <core-header-panel main >

            <core-toolbar class="medium" id="barre2">
                <!-- TOP TOOLBAR -->
                <core-icon-button id="navicon" icon="menu"></core-icon-button>
                <!--<paper-test></paper-test>-->
                <menu-toolbar-hsds></menu-toolbar-hsds>
                <paper-input id="search-mainpage-input" label="Rechercher"></paper-input>
                <core-icon-button icon="search"></core-icon-button>

                <paper-dialog  class="size-position"  >
                    <?php
                    if (isset($_SESSION['nbproduit'])) {
                        foreach ($_SESSION['nbproduit'] as $key => $prod) {
//                              var_dump($prod);
                            echo "<core-icon-button icon='cancel' onclick='alert()'></core-icon-button>";
                            echo $prod['nom'] . "</br>";
                        }
                    }
                    ?>
                </paper-dialog>

                <template is="auto-binding">
                    <?php include_once("../application/views/scripts/panier/index.phtml"); ?>


                    <input type="hidden" id="nbproduit" value="0"><p id="panier"></p>
                    <?php if (!isset($_SESSION['email'])) { ?>
                        <paper-button  id="connexion-button" label="CONNEXION"  on-tap="{{toggleDialog1}}" ></paper-button>
                        <paper-dialog heading="CONNEXION" class="size-position" >
                            <core-form-connexion></core-form-connexion>
                        </paper-dialog>
                        <paper-button  id="inscription-button" label="INSCRIPTION" onclick="toggleDialog('paper-dialog-transition-center')" ></paper-button>

                        <paper-dialog heading="Inscription" transition="paper-dialog-transition-center">
                            <core-form-inscription>           
                            </core-form-inscription>
                        </paper-dialog>
                        <?php
                    } else {
                        
                        if ($_SESSION["role"] == "user") {
                            echo "<a href=" . $this->url(array('controller' => 'profil',
                                'action' => 'index')) . "/><core-icon icon='account-circle'></core-icon></a>";
                        } else {
                            echo "<a href =" . $this->url(array('controller' => 'backoffice_connexion', 'action' => 'index')) . ">Backoffice</a>";
                            echo "<a href=" . $this->url(array('controller' => 'profil',
                                'action' => 'index')) . "/><core-icon icon='account-circle'></core-icon></a>";
                        }

                        echo "<p>" . $_SESSION['email'] . "</p>";
                        ?>
                        <core-icon-button icon="more-vert"></core-icon-button>
                        <?php
                    }
                    ?>

                </template>        
            </core-toolbar>

            <submenu-mainpage></submenu-mainpage>

            <?php
            echo $this->layout()->content;
            ?>  

        </core-header-panel>

    </core-drawer-panel>

</body>

<script type="text/javascript">
    //
    //    function addName() {
    //        var recup = document.querySelectorAll("hello-john-doe")[0];
    //        document.querySelector("buddies-list").buddies.push({name: recup.name});
    //    }
    //    ;
    function toggleDialog(transition) {
        var dialog = document.querySelector('paper-dialog[transition=' + transition + ']');
        dialog.toggle();
    }
    ;

    var MonTableau = new Array();


    var scope = document.querySelector('template[is=auto-binding]');

    scope.toggleDialog1 = function (e) {
//                if (e.target.localName != 'paper-button') {
//                    return;
//                }
        var d = e.target.nextElementSibling;
        if (!d) {
            return;
        }
        d.toggle();
    };


    var content = document.getElementById('super-template');
    //alert(content);
    var nav = document.getElementById('navicon');
    //alert(nav);
    content.addEventListerner('template-bound', function () {
        console.log(document.query - selector('navicon'));
    })

    //    document.addEventListener('polymer-ready', function(){
    //        var navicon=document.getElementById('navicon');
    //        alert(navicon);
    //        var drawerPanel=document.getElementById('drawerPanel');
    //        navicon.addEventListener('click',function(){
    //            drawerPanel.togglePanel();
    //        });
    //    });





</script>
</html>